name: march
channels:
  - conda-forge
dependencies:
  - python=3.10
  - cudatoolkit-dev=11.7.0
  - cudatoolkit=11.8.0
  - nvidia-apex=22.03
  - pip
  - pip:
    - torch --extra-index-url https://download.pytorch.org/whl/cu117
    - -r requirements.txt
    - deepspeed==0.9.1
    - mpi4py==3.1.4
    - git+https://github.com/NVIDIA/apex -v --disable-pip-version-check --no-cache-dir --global-option="--cpp_ext" --global-option="--cuda_ext"
