name: march
channels:
  - conda-forge
dependencies:
  - python=3.10
  - cudatoolkit-dev=11.7.0
  - cudatoolkit=11.8.0
  - pip
  - pip:
    - torch --extra-index-url https://download.pytorch.org/whl/cu117
    - -r requirements.txt
    - deepspeed==0.9.1
    - mpi4py==3.1.4
    - torchtyping==0.1.4
    - transformers==4.28.1
    - sentencepiece==0.1.98
    - accelerate==0.18.0
    - datasets==2.11.0
    - tensorboard==2.12.0
    - -e .
